# Generated by Django 6.0.4 on 2026-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
    ]
